data:
  parquet_dir: "C:\Users\Administrator\Desktop\Project\feature_ranking\data_sets"
  sys_col: ['msisdn_key', 'tac', 'date_of_birth', 'id_expiry_date', 'bucket','MoMo_rch_centric_perc','WeekendToWeekdayDataRatio', 'CrossServiceRatio', 'voice_centric_perc']
  cat_var: ['data_day_pref','voice_day_pref' ,'voice_usage_pattern', 'voice_rev_pattern', 'date_key', 'os_name', 'device_category','hs_make','hs_model', 'edge_ind','activation_date','gen_type','gender','activated_via','tariff_code','subscriber_category','subscriber_sub_category']

processing:
  num_sample: 5
  sample_size: 500

logging:
  level: INFO
  filename: logs/app.log
