data:
  exclude:
    sys_col: ['msisdn_key', 'tac', 'date_of_birth', 'id_expiry_date', 'bucket', 'CrossServiceRatio', 'voice_centric_perc']
    cat_var: ['voice_day_pref' ,'voice_usage_pattern', 'voice_rev_pattern', 'date_key', 'os_name', 'device_category','hs_make','hs_model', 'edge_ind','activation_date','gen_type','gender','activated_via','tariff_code','subscriber_category','subscriber_sub_category']
  include:
    loc_col: ["msisdn_key", "weekday_weekend_diff_site_dist_mu_day","weekday_weekend_diff_site_dist_mu_night", "avg_site_dist_mu_day","avg_site_dist_mu_night","avg_site_dist_day_night","location_diversity_index", "average_distance", "temporal_variability_index"]
    loc_col1: ['msisdn_key', 'VoiceRev', 'DataRev', 'TotalRevenue', 'VoiceOutMins',
       'DataUsageMb', 'RechargeAmt', 'VoiceDOU', 'BalanceDaily', 'MomoBalance',
       'dola', 'Avg_dola', 'DataDOU', 'RechargeEvents', 'CallDuration',
       'Onnet_Ratio', 'Int_Ratio', 'Inc_Out_Ratio', 'voice_day_pref',
       'voice_centric_perc', 'TotalMinutes', 'CrossServiceRatio',
       'WeekendToWeekdayVoiceRatio', 'RoamingVoiceUsageIntensity',
       'voice_usage_pattern']

output_files:
    pd_summary: "pd_summary.csv"
    travel_segment_summary: "Travel_segment_summary.csv"
    travel_segment_var: "Travel_segment_var.csv"
    travel_corr_matrix: "Travel_corr_matrix.csv"
    non_travel_segment_summary: "Non_Travel_segment_summary.csv"
    non_travel_segment_var: "Non_Travel_segment_var.csv"
    non_travel_corr_matrix: "Non_Travel_corr_matrix.csv"
    travel_feature_importance: "Travel_featureimp.csv"

directory:
  parquet: "C:\\Users\\Administrator\\Desktop\\Project\\Feature-Selection\\data_sets"
  output: "C:\\Users\\Administrator\\Desktop\\Project\\Feature-Selection\\data_sets\\download"
  location: "C:\\Users\\Administrator\\Desktop\\Project\\Feature-Selection\\data_sets\\location"
  

feature_ranking:
  num_sample: 1
  sample_size: 50
  var_type: mixed

logging:
  level: INFO
  filename: logs/app.log

model:
  n_estimators: 100
  test_size: 0.3
  random_state: 42
  drop_col: ['HighTraveller', 'avg_site_dist_day_night', 'location_diversity_index']

segment:
  dist_col: "RechargeAmt"
  quantile1: 0.75
  div_col: "temporal_variability_index"
  quantile2: 0.75
  seg_col: "IrregularRecharge"